### ISSUE TITLE
Iterator on client.resource with 'dataset' & 'feedback' as resource fails with error 'Not Supported' 

### ISSUE THREAD

**Issue by maxderooijtopicus** [mopinion/mopinion-python-api#5]
Hi,

When I create an iterator with client.resource('datasets', <DATASET_ID>, 'feedback', iterator=True) I can request the first page of results just fine. The following `next(iterator)` call gives me the following error:

`ValueError: Resource '/datasets/<DATASET_ID>/feedback?page=2' is not supported.`

This behaviour is not happening with other resources like report + fields for example. The iterator especially on feedback items would be very valuable to reduce custom code for looping over all feedback items.

Any ideas how to solve or is this something that needs to be developed?

**Comment by mopinion-support** [comment]
Goodmorning Max,
Thanks for opening this issue. We will investigate this futher and let you know you.
Kind regards,
Pieter

**Comment by maxderooijtopicus** [comment]
Hi again,

Here is some example code that gives me the error. Maybe I am overlooking something fundamental to generators here. 

```
iterator_mopinion = client.resource("datasets", 123456, "feedback", iterator=True)

for page in iterator_mopinion:
    print(page.json()['data'])
```

**Comment by maxderooijtopicus** [comment]
Hi! Any updates on this one or ways we can contribute?

**Comment by Piethot** [comment]
Hi Max,
We will add the pagination support for the datasets endpoint as well. I will let you know when it is available.
Kind regards,
Pieter
